import os
import re

def rename_files():
    directory = "data/Kunde_Structured_Output/"
    files_renamed_count = 0

    # Ensure the directory exists
    if not os.path.isdir(directory):
        print(f"Error: Directory '{directory}' not found.")
        return

    filenames = os.listdir(directory)
    filenames.sort() # Process in a predictable order, helps with potential conflicts if any

    # Handle specific cases first to avoid conflicts if they were to be generated by the general rule
    # Case 1: Kunde.md -> Kunde 1.md
    old_name_kunde1 = os.path.join(directory, "Kunde.md")
    new_name_kunde1 = os.path.join(directory, "Kunde 1.md")
    if os.path.exists(old_name_kunde1):
        if not os.path.exists(new_name_kunde1) or old_name_kunde1 == new_name_kunde1:
            try:
                os.rename(old_name_kunde1, new_name_kunde1)
                print(f"Renamed '{old_name_kunde1}' to '{new_name_kunde1}'")
                files_renamed_count += 1
            except OSError as e:
                print(f"Error renaming '{old_name_kunde1}' to '{new_name_kunde1}': {e}")
        else:
            print(f"Skipping rename of '{old_name_kunde1}': target '{new_name_kunde1}' already exists.")

    # Case 2: Kunde2.md -> Kunde 2.md
    old_name_kunde2 = os.path.join(directory, "Kunde2.md")
    new_name_kunde2 = os.path.join(directory, "Kunde 2.md")
    if os.path.exists(old_name_kunde2):
        if not os.path.exists(new_name_kunde2) or old_name_kunde2 == new_name_kunde2:
            try:
                os.rename(old_name_kunde2, new_name_kunde2)
                print(f"Renamed '{old_name_kunde2}' to '{new_name_kunde2}'")
                files_renamed_count += 1
            except OSError as e:
                print(f"Error renaming '{old_name_kunde2}' to '{new_name_kunde2}': {e}")
        else:
            print(f"Skipping rename of '{old_name_kunde2}': target '{new_name_kunde2}' already exists.")

    # Refresh file list after specific renames
    filenames = os.listdir(directory)
    filenames.sort()

    # Handle general cases: Kunde copy X.md -> Kunde X.md
    for filename in filenames:
        if filename.startswith("Kunde copy ") and filename.endswith(".md"):
            match = re.match(r"Kunde copy (\d+)\.md", filename)
            if match:
                number = match.group(1)
                old_path = os.path.join(directory, filename)
                new_filename = f"Kunde {number}.md"
                new_path = os.path.join(directory, new_filename)

                if old_path == new_path:
                    continue # Already correctly named

                if not os.path.exists(new_path):
                    try:
                        os.rename(old_path, new_path)
                        print(f"Renamed '{old_path}' to '{new_path}'")
                        files_renamed_count += 1
                    except OSError as e:
                        print(f"Error renaming '{old_path}' to '{new_path}': {e}")
                else:
                    print(f"Skipping rename of '{filename}': target '{new_filename}' already exists.")
            else:
                print(f"Skipping '{filename}': does not match expected 'Kunde copy X.md' pattern correctly.")
        elif filename == "Kunde.md" or filename == "Kunde2.md":
            # Already handled or should have been, skip to avoid re-processing
            continue

    if files_renamed_count == 0:
        print("No files were renamed. Check if files are already correctly named or if patterns need adjustment.")
    else:
        print(f"\nFinished renaming. Total files renamed: {files_renamed_count}")

if __name__ == "__main__":
    rename_files()